yatube/core/urls.py
handler404 = 'core.views.page_not_found'

yatube/posts/urls.py
"""Подключение модулей."""
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.post_create, name='post_create'),
    path('create/group/', views.group_create, name='group_create'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
"""Подключение модулей."""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

yatube/posts/models.py
"""Подключение модулей."""
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()
COUNT_CHAR_POST_TEXT = 15


class Group(models.Model):
    """Класс Group."""
    title = models.CharField(
        max_length=200,
        verbose_name='Title группы',
        help_text='Введите тайтл группы',
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Slug группы',
        help_text='Введите слаг группы',
    )
    description = models.TextField(
        verbose_name='Описание группы',
        help_text='Введите описание группы',
    )

    def __str__(self) -> str:
        return self.title

    class Meta:
        """Класс Meta для Group описание метаданных."""
        verbose_name = 'group'
        verbose_name_plural = 'groups'


class Post(models.Model):
    """Класс Post."""
    text = models.TextField(
        verbose_name='Текст',
        help_text='Введите текст поста',
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        related_name='posts',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self) -> str:
        return self.text[:COUNT_CHAR_POST_TEXT]

    class Meta:
        """Класс Meta для Posts описание метаданных."""
        ordering = ('-pub_date',)
        verbose_name = 'post'
        verbose_name_plural = 'posts'


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
    )
    text = models.TextField(
        verbose_name='Текст',
        help_text='Введите текст комментария',
    )
    created = models.DateTimeField(
        verbose_name='Дата создания',
        auto_now_add=True,
    )

    def __str__(self) -> str:
        return self.text[:COUNT_CHAR_POST_TEXT]

    class Meta:
        """Класс Meta для Comment описание метаданных."""
        verbose_name = 'comment'
        verbose_name_plural = 'comments'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE,
    )
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE,
    )

    def __str__(self) -> str:
        return self.user.username

    class Meta:
        """Класс Meta для Follow описание метаданных."""
        verbose_name = 'follow'
        verbose_name_plural = 'follows'

yatube/posts/forms.py
from django import forms

from .models import Comment, Group, Post

COUNT_CHAR_TEXT = 10


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')

    def clean_text(self):
        data = self.cleaned_data['text']
        if len(data) < COUNT_CHAR_TEXT:
            raise forms.ValidationError('Поле должно быть больше 10')
        return data


class GroupForm(forms.ModelForm):

    description = forms.CharField(widget=forms.Textarea, required=False)

    class Meta:
        model = Group
        fields = ('title', 'slug', 'description')

    def clean_slug(self):
        data = self.cleaned_data['slug']
        if len(data) > COUNT_CHAR_TEXT:
            raise forms.ValidationError('Поле должно быть меньше 10')
        return data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
"""Подключение модулей."""
from django.contrib.auth.decorators import login_required
from django.core.paginator import Page, Paginator
from django.db.models import QuerySet
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .forms import CommentForm, GroupForm, PostForm
from .models import Follow, Group, Post, User

COUNT_POSTS = 10


def paginator_page(request, posts: QuerySet) -> Page:
    """Функция для пагинации страниц."""
    paginator = Paginator(posts, COUNT_POSTS)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


def index(request):
    """Viev-функция главной страницы."""
    template = 'posts/index.html'
    posts = Post.objects.all()
    page_obj = paginator_page(request, posts)
    context = {
        'page_obj': page_obj,
        'index': True,
    }
    return render(request, template, context)


def group_posts(request, slug):
    """Viev-функция страниц групп."""
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = paginator_page(request, posts)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    """Viev-функция для страницы профиля."""
    template = 'posts/profile.html'
    user = get_object_or_404(User, username=username)
    following = (not request.user.is_anonymous) and (
        Follow.objects.filter(
            user=request.user,
            author=user
        ).exists()
    )
    posts_list = user.posts.all()
    page_obj = paginator_page(request, posts_list)
    context = {
        'author': user,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    """Viev-функция страниц поста."""
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    comment_list = post.comments.all()
    form = CommentForm()
    context = {
        'post': post,
        'comments': comment_list,
        'form': form,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    """Viev-функция для создания поста."""
    template = 'posts/create_post.html'
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect(
            reverse('posts:profile', args=[request.user.username])
        )
    return render(request, template, {'form': form})


@login_required
def group_create(request):
    """Viev-функция для создания группы."""
    template = 'posts/create_group.html'
    form = GroupForm(request.POST or None)
    if form.is_valid():
        group = form.save(commit=False)
        group.save()
        return redirect(
            reverse('posts:group_list', args=[group.slug])
        )
    return render(request, template, {'form': form})


@login_required
def post_edit(request, post_id):
    """Viev-функция для редактирования поста."""
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect(
            reverse('posts:post_detail', args=[post.id])
        )
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect(
            reverse('posts:post_detail', args=[post.id])
        )
    context = {
        'is_edit': True,
        'id': post.id,
        'form': form,
    }
    return render(request, template, context)


@login_required
def post_delete(request, post_id):
    template = 'posts/post_delete.html'
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect(
            reverse('posts:post_detail', args=[post.id])
        )
    id = post.id
    context = {
        'is_edit': True,
        'id': id,
    }
    post.delete()
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    """Viev-функция для редактирования поста."""
    form = CommentForm(request.POST or None)
    post = get_object_or_404(Post, pk=post_id)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """Viev-функция для подписок."""
    template = 'posts/follow.html'
    user = request.user
    posts_list = Post.objects.filter(author__following__user=request.user)
    page_obj = paginator_page(request, posts_list)
    context = {
        'author': user,
        'page_obj': page_obj,
        'follow': True,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    """Viev-функция для оформления подписки."""
    user = request.user
    follow = get_object_or_404(User, username=username)
    if follow != user:
        Follow.objects.get_or_create(
            user=user,
            author=follow
        )
    return redirect(reverse('posts:follow_index'))


@login_required
def profile_unfollow(request, username):
    """Viev-функция для отписки."""
    author = get_object_or_404(User, username=username)
    follow = Follow.objects.filter(
        user=request.user,
        author=author,
    )
    follow.delete()
    return redirect(reverse('posts:follow_index'))

yatube/templates/includes/comment.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %} 

yatube/templates/includes/footer.html
<p class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © {% now "Y" %} Copyright <span style="color:red">Ya</span>tube
</p>

yatube/templates/includes/form.html
{% load user_filters %}
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
      {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
       {{ error|escape }}
    </div>
   {% endfor %}
{% endif %}
{% if SHOW_USERNAME %}
  <input type="hidden" name="csrfmiddlewaretoken" value="">
  <div class="form-group row my-3 p-3">
    <label for="id_username">
       Имя пользователя ---- {{  request.user.username }}
    </label>
  </div>
{% endif %}
{% csrf_token %}
{% for field in form %}
  <div class="form-group row my-3 p-3">
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
        {% if field.field.required %}
          <span class="required text-danger">*</span>
        {% endif %}
      </label>
    {{ field|addclass:'form-control' }}
    {% if field.help_text %}
      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
        {{ field.help_text|safe }}
      </small>
    {% endif %}
  </div>
{% endfor %}

yatube/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}  
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      <ul class="nav nav-pills">
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
          href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
           href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if user.is_authenticated %} 
          <li class="dropdown">
            <button class="btn dropdown-toggle" type="button"
              id="create" data-toggle="dropdown" aria-haspopup="true" 
              aria-expanded="false">Создать</button>
            <div class="dropdown-menu" aria-labelledby="create">
                <a class="dropdown-item {% if view_name  == 'posts:post_create' %}active{% endif %}"
                href="{% url 'posts:post_create' %}">Новую запись</a>
                <a class="dropdown-item {% if view_name  == 'posts:group_create' %}active{% endif %}"
                href="{% url 'posts:group_create' %}">Новую группу</a>
            </div>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light  {% if view_name  == 'users:password_change' %}active{% endif %}" 
            href="{% url 'users:password_change' %}">Изменить пароль</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}" 
            href="{% url 'users:logout' %}">Выйти</a>
          </li>
          <li>
            Пользователь: {{ user.username }}
          </li>
        {% else %}
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}" 
            href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}" 
            href="{% url 'users:signup' %}">Регистрация</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
{% endwith %} 

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Предыдущая
          </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Следующая
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}    
    </ul>
  </nav>
{% endif %}

yatube/templates/includes/post.html
{% load thumbnail %}
<article class="row">
  <ul class="col-3">
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p class="col-6">
    {% thumbnail post.image "560x300" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    {{ post.text }}
  </p>
  <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
  {% if SHOW_GROUP_LINK and post.group  %}
    <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
  {% endif %}
  {% if SHOW_PROFILE_LINK %}
    <a href="{% url 'posts:profile' post.author.username %}">Профиль автора</a>
  {% endif %}
</article>
{% if not forloop.last %}<hr>{% endif %}

yatube/templates/includes/switcher.html
{% if user.is_authenticated %}
<div class="row my-3">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a 
        class="nav-link {% if index %}active{% endif %}"
        href="{% url 'posts:index' %}"
      >
        Все авторы
      </a>
    </li>
    <li class="nav-item">
      <a 
         class="nav-link {% if follow %}active{% endif %}"
         href="{% url 'posts:follow_index' %}"
      >
        Избранные авторы
      </a>
    </li>
  </ul>
</div>
{% endif %}