yatube/core/urls.py
handler404 = 'core.views.page_not_found'

yatube/posts/urls.py
"""Подключение модулей."""
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.post_create, name='post_create'),
    path('create/group/', views.group_create, name='group_create'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
"""Подключение модулей."""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

yatube/posts/models.py
"""Подключение модулей."""
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()
COUNT_CHAR_POST_TEXT = 15


class Group(models.Model):
    """Класс Group."""
    title = models.CharField(
        max_length=200,
        verbose_name='Title группы',
        help_text='Введите тайтл группы',
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Slug группы',
        help_text='Введите слаг группы',
    )
    description = models.TextField(
        verbose_name='Описание группы',
        help_text='Введите описание группы',
    )

    def __str__(self) -> str:
        return self.title

    class Meta:
        """Класс Meta для Group описание метаданных."""
        verbose_name = 'group'
        verbose_name_plural = 'groups'


class Post(models.Model):
    """Класс Post."""
    text = models.TextField(
        verbose_name='Текст',
        help_text='Введите текст поста',
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        related_name='posts',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self) -> str:
        return self.text[:COUNT_CHAR_POST_TEXT]

    class Meta:
        """Класс Meta для Posts описание метаданных."""
        ordering = ('-pub_date',)
        verbose_name = 'post'
        verbose_name_plural = 'posts'


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
    )
    text = models.TextField(
        verbose_name='Текст',
        help_text='Введите текст комментария',
    )
    created = models.DateTimeField(
        verbose_name='Дата создания',
        auto_now_add=True,
    )

    def __str__(self) -> str:
        return self.text[:COUNT_CHAR_POST_TEXT]

    class Meta:
        """Класс Meta для Comment описание метаданных."""
        verbose_name = 'comment'
        verbose_name_plural = 'comments'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE,
    )
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE,
    )

    def __str__(self) -> str:
        return self.user.username

    class Meta:
        """Класс Meta для Follow описание метаданных."""
        verbose_name = 'follow'
        verbose_name_plural = 'follows'

yatube/posts/forms.py
from django import forms

from .models import Comment, Group, Post

COUNT_CHAR_TEXT = 10


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')

    def clean_text(self):
        data = self.cleaned_data['text']
        if len(data) < COUNT_CHAR_TEXT:
            raise forms.ValidationError('Поле должно быть больше 10')
        return data


class GroupForm(forms.ModelForm):

    description = forms.CharField(widget=forms.Textarea, required=False)

    class Meta:
        model = Group
        fields = ('title', 'slug', 'description')

    def clean_slug(self):
        data = self.cleaned_data['slug']
        if len(data) > COUNT_CHAR_TEXT:
            raise forms.ValidationError('Поле должно быть меньше 10')
        return data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
"""Подключение модулей."""
from django.contrib.auth.decorators import login_required
from django.core.paginator import Page, Paginator
from django.db.models import QuerySet
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .forms import CommentForm, GroupForm, PostForm
from .models import Follow, Group, Post, User

COUNT_POSTS = 10


def paginator_page(request, posts: QuerySet) -> Page:
    """Функция для пагинации страниц."""
    paginator = Paginator(posts, COUNT_POSTS)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


def index(request):
    """Viev-функция главной страницы."""
    template = 'posts/index.html'
    posts = Post.objects.all()
    page_obj = paginator_page(request, posts)
    context = {
        'page_obj': page_obj,
        'index': True,
    }
    return render(request, template, context)


def group_posts(request, slug):
    """Viev-функция страниц групп."""
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = paginator_page(request, posts)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    """Viev-функция для страницы профиля."""
    template = 'posts/profile.html'
    user = get_object_or_404(User, username=username)
    following = (not request.user.is_anonymous) and (
        Follow.objects.filter(
            user=request.user,
            author=user
        ).exists()
    )
    posts_list = user.posts.all()
    page_obj = paginator_page(request, posts_list)
    context = {
        'author': user,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    """Viev-функция страниц поста."""
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    comment_list = post.comments.all()
    form = CommentForm()
    context = {
        'post': post,
        'comments': comment_list,
        'form': form,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    """Viev-функция для создания поста."""
    template = 'posts/create_post.html'
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect(
            reverse('posts:profile', args=[request.user.username])
        )
    return render(request, template, {'form': form})


@login_required
def group_create(request):
    """Viev-функция для создания группы."""
    template = 'posts/create_group.html'
    form = GroupForm(request.POST or None)
    if form.is_valid():
        group = form.save(commit=False)
        group.save()
        return redirect(
            reverse('posts:group_list', args=[group.slug])
        )
    return render(request, template, {'form': form})


@login_required
def post_edit(request, post_id):
    """Viev-функция для редактирования поста."""
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect(
            reverse('posts:post_detail', args=[post.id])
        )
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect(
            reverse('posts:post_detail', args=[post.id])
        )
    context = {
        'is_edit': True,
        'id': post.id,
        'form': form,
    }
    return render(request, template, context)


@login_required
def post_delete(request, post_id):
    template = 'posts/post_delete.html'
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect(
            reverse('posts:post_detail', args=[post.id])
        )
    id = post.id
    context = {
        'is_edit': True,
        'id': id,
    }
    post.delete()
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    """Viev-функция для редактирования поста."""
    form = CommentForm(request.POST or None)
    post = get_object_or_404(Post, pk=post_id)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """Viev-функция для подписок."""
    template = 'posts/follow.html'
    user = request.user
    posts_list = Post.objects.filter(author__following__user=request.user)
    page_obj = paginator_page(request, posts_list)
    context = {
        'author': user,
        'page_obj': page_obj,
        'follow': True,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    """Viev-функция для оформления подписки."""
    user = request.user
    follow = get_object_or_404(User, username=username)
    if follow != user:
        Follow.objects.get_or_create(
            user=user,
            author=follow
        )
    return redirect(reverse('posts:follow_index'))


@login_required
def profile_unfollow(request, username):
    """Viev-функция для отписки."""
    author = get_object_or_404(User, username=username)
    follow = Follow.objects.filter(
        user=request.user,
        author=author,
    )
    follow.delete()
    return redirect(reverse('posts:follow_index'))

yatube/templates/posts/create_group.html
{% extends 'base.html' %}
{% block title %}
{% if is_edit %}
  Редактировать запись id = {{ id }}
{% else %}
  Добавить группу
{% endif %}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактировать запись id = {{ id }}
            {% else %}
              Добавить группу
            {% endif %}
          </div>
          <div class="card-body">
            {% if is_edit %}
              <form method="post" action="{% url 'posts:post_edit'  id  %}">
            {% else %}
              <form method="post" action="{% url 'posts:group_create' %}">
            {% endif %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary">
              {% if is_edit %}
                Сохранить
              {% else %}
                Добавить
              {% endif %}
            </button>
            </form>
          </div> 
        </div> 
      </div> 
    </div>
  </div>
{% endblock %}

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
{% if is_edit %}
  Редактировать запись id = {{ id }}
{% else %}
  Добавить запись
{% endif %}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактировать запись id = {{ id }}
            {% else %}
              Добавить запись
            {% endif %}
          </div>
          <div class="card-body">
            {% if is_edit %}
              <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_edit'  id  %}">
            {% else %}
              <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_create' %}">
            {% endif %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary">
              {% if is_edit %}
                Сохранить
              {% else %}
                Добавить
              {% endif %}
            </button>
            </form>
          </div> 
        </div> 
      </div> 
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
  Подписки пользователя
{% endblock %}
{% block content %}
{% include 'includes/switcher.html' %} 
  <div class="container py-5">
    <h1 class="card-header"> Подписки пользователя </h1>
    {% for post in page_obj %}
      {% include 'includes/post.html' with SHOW_GROUP_LINK=True SHOW_PROFILE_LINK=True %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Записи сообщества {{ group|title }}
{% endblock %}
{% block content %}

  <div class="container py-5">
    <h1> {{ group.title }} </h1>
    <p> {{ group.description }} </p>
    {% for post in page_obj %}
      {% include 'includes/post.html' with SHOW_PROFILE_LINK=True %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
  {% include 'includes/switcher.html' %} 
  <div class="container py-5">
    <h1 class="card-header"> Последние обновления на сайте </h1>
    {% load cache %}
    {% cache 20 index_page page_obj.number %}
    {% for post in page_obj %}
      {% include 'includes/post.html' with SHOW_GROUP_LINK=True SHOW_PROFILE_LINK=True %}
    {% endfor %}
    {% endcache %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/post_delete.html
{% extends 'base.html' %}
{% block title %}
 Пост {{ id }} успешно удален
{% endblock %}
{% block content %}
  <article>
    <h1>Пост {{ id }} успешно удален</h1>
    <a href="{% url 'posts:index' %}">
      Вернутся на главную страницу
    </a>
  </article>
{% endblock %}  

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
 Пост {{  post.author.username|truncatewords:30  }}
{% endblock %}
{% block content %}
  <h1> Создатель поста - {{ post.author.username}} </h1>
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        <li class="list-group-item">
          Группа: {{ post.group }}
        {% if post.group  %}
          <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
        {% endif %}
        </li>
        <li class="list-group-item">
          Автор: {{post.author.get_full_name}}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "560x539" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p> {{post.text}} </p>
      {% if post.author == user %}
        <div class="row">
          <aside class="col-9 col-md-3">
            <button type="submit" class="btn btn-dark">
              <a href="{% url 'posts:post_edit' post.id %}" style="color: #ffffff">
                Редактировать запись
              </a>
            </button>
          </aside>
          <aside class="col-9 col-md-6">
            <form action="{% url 'posts:post_delete' post.id %}"  
              class="btn btn-danger" style="color: #ffffff" method="post">
              {% csrf_token %}
              <button onclick="return confirm('Are you sure?');">Удалить запись</button>
            </form>
          </aside>
        </div>
      {% endif %}
      {% include 'includes/comment.html' %}
    </article>
  </div>
{% endblock %}  

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
 Профайл пользователя {{ author.username }}
{% endblock %}
{% block content %}
  <div class="container py-5">        
    <h1>Все посты пользователя {{ author.username }} </h1>
    <h3>Всего постов: {{ page_obj.paginator.count }} </h3>  
    {% if user.is_authenticated %} 
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
      {% endif %} 
    {% endif %} 
    {% for post in page_obj %}
      {% include 'includes/post.html' with SHOW_GROUP_LINK=True %}
    {% endfor %}
    <hr>
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}  